# Site settings
title: notes by jared davis
email: message@jared-pri.me
description: "Ruby and Go. Haskell wannabe. Mathematics enthusiast and literature lover. Just another backend data-plumber ğŸ‘"
baseurl: ""
url: "http://jared-pri.me"
github_username: jared-prime
# Build settings
markdown: kramdown
permalink: pretty
